"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/globals.css";
import Header from "@/components/Header";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [isColorMode, setIsColorMode] = useState<boolean>(false);
  const toggleColorMode = () => {
    setIsColorMode(prevMode => !prevMode);
  }
 
  return (
    <html lang="en">
      <body className={`${inter.className} ${isColorMode ? 'color' : ""}`} >
        <Header toggleColorMode={toggleColorMode} isColorMode={isColorMode} />
        {children}
      </body>
    </html>
  );
}
